### ISSUE TITLE
Odd behavior with docker

### ISSUE THREAD

**Issue by Yey007** [sidorares/node-mysql2#1245]
Hello,

Please let me know if you think this does not fall under your domain.
I'm attempting to connect to a mysql database running in docker, with my app also running in docker. They are ran together using docker-compose. If I try to connect to the database using this library, it seems to always attempt to use the wrong IP address, and I get a connection refused error. For example, when I pass "db" as the host like this:

```
let conn = createConnection({
    host: "db",
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE
});
```
It gives the error `Error: connect ECONNREFUSED 127.0.0.1:3306` (note `127.0.0.1`). I also tried resolving "db" and using that address:

```
let conn = createConnection({
    host: "192.168.80.2",
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    database: process.env.MYSQL_DATABASE
});
```

But got the same error. I am 99% sure all of my environment variable are correct and that the mysql container is running when it attempts to connect (it always restarts the container)

Here is my docker-compsose file:
```
version: "3.8"

services: 
  bot:
    container_name: bot
    image: yey007/transcriberbot:latest
    depends_on: 
      - db
    env_file:
      - .env
    restart: always
    networks:
      - my_network
  
  db:
    container_name: database
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file: 
      - db.env
    restart: always
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
```

Again, please let me know if this doesn't fall under your domain. I've troubleshooted a lot and am pretty sure I haven't severely messed anything up, so I came to ask here. Thank you!
