### ISSUE TITLE
Pool not releasing connections

### ISSUE THREAD

**Issue by danj1980** [sidorares/node-mysql2#2493]
All of my queries include dbConnection.release(), however the connections do not get released and once connectionLimit is reached, the execution pauses waiting for an available connection.

I've re-worked my code so that every pool.getConnection() has a dbConnection.release() right next to it, to make absolutely certain that I'm not accidentally leaving any connections unreleased.

However, this did not help, and it seems that there is a bug in the releasing of pool connections.

I store my pool in a static variable with a class called Global.

```
class globals
{
	static dbPool = null;
}
```

Runs once on startup
```
globals.dbPool = await mysql.createPool({
				host: databaseServer,
				port: databasePort,
				user: databaseUsername,
				password: databasePassword,
				database: databaseName,
				connectionLimit: 10
			});

```
Example usage
            ```
            const dbConnection = await globals.dbPool.getConnection();

            let mysqlResponse = null;

            await dbConnection.query(`SELECT * FROM guild;`).then(result => {
                mysqlResponse = result[0];

            }).catch(err => console.log(err));

            dbConnection.release();
```
Result after some queries have been executed 
![image](https://github.com/sidorares/node-mysql2/assets/12071228/17c7aca3-567e-4202-8ebe-b202fcba6c5d)

**Comment by danj1980** [comment]
![image](https://github.com/sidorares/node-mysql2/assets/12071228/aa83ce7b-a10a-42b8-a405-3433d43bb2b3)

**Comment by danj1980** [comment]
It seems I've found the issue.

If maxIdle is not set on the pool, _removeIdleTimeoutConnections is never executed, and therefore there is never any cleanup of released connections.
I think it's this line that's the problem.
https://github.com/sidorares/node-mysql2/blob/b87ee4456556712cb8b0538f2f264d9a9fe5764a/lib/pool.js#L30

**Comment by danj1980** [comment]
Side note, if I manually kill a connection on MySQL server, execution continues in the pool until the connections fill back up again.

**Comment by danj1980** [comment]
> Hi @danj1980, 🙋🏻‍♂️
> 
> It's not directly related, but can you check if this _PR_ affects this behavior in some way?
> 
> * [fix: removal failure of freeConnection causing infinite loop #2171](https://github.com/sidorares/node-mysql2/pull/2171)
> 
I dont think that's the same issue, as the CPU usage is 0% when the connections run out.

> Also, this workaround:
> 
> * [Uncaught exception in pool.query #2317 (comment)](https://github.com/sidorares/node-mysql2/issues/2317#issuecomment-1859841319)

This workaround looks similar to my test where I'm getting a connection, querying it, and then immediately releasing it.

**Comment by wellwelwel** [comment]
> This workaround looks similar to my test where I'm getting a connection, querying it, and then immediately releasing it.

@danj1980, can you provide a minimal repro for this issue?

---

According to the documentation, this should be the default behavior for `maxIdle`:

```js
{
  connectionLimit: 10,
  maxIdle: 10, // max idle connections, the default value is the same as `connectionLimit`
}
```

**Comment by danj1980** [comment]
I'm sorry. Let me clarify my fix....

In order to get it to cleanup old released connections, I had to set maxIdle < connectionLimit.

If maxIdle is default (eg. maxIdle => connectionLimit), no cleanup of old released connections occurs as shown below.

https://github.com/sidorares/node-mysql2/blob/b87ee4456556712cb8b0538f2f264d9a9fe5764a/lib/pool.js#L30

**Comment by wellwelwel** [comment]
So, currently there are these tests for idle connections:

https://github.com/sidorares/node-mysql2/blob/0ce7081e5028c82d861d967ba730b28c7e7bada6/test/integration/test-pool-release-idle-connection.test.cjs#L6-L45

But unfortunately, I can't reproduce this behavior to implement a specific test case for it 😕

**Comment by danj1980** [comment]
In that test, 
Try removing maxIdle so it's default.
Then run the test, pause in the middle for at least 5 seconds to allow idleTimeout to be reached, and then see if it releases the connections that have reached the idleTimeout.

I'd try it myself but I dont know how to run those tests.

**Comment by wellwelwel** [comment]
Thanks, @danj1980 🚀

I'll show how I perform the tests locally using **Docker**, but you can also see the [**Contributing.md**](https://github.com/sidorares/node-mysql2/blob/master/Contributing.md).

---

### Choose a directory

> For this example, I'll use the `Desktop`

```bash
mkdir -p Desktop/sidorares
cd Desktop/sidorares
```

### Clone this repository

```bash
git clone https://github.com/sidorares/node-mysql2.git
```

### Create a Docker Compose file

`Desktop/sidorares/docker-compose.yml`:

```yml
version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root']
      interval: 10s
      timeout: 5s
      retries: 5
      
  node-mysql2:
    image: node:lts-alpine
    working_dir: /usr/app
    volumes:
      - ./node-mysql2:/usr/app
    command: npm run test
    environment:
      MYSQL_HOST: db
      FILTER: test-pool-release-idle-connection
    depends_on:
      db:
        condition: service_healthy
```

Then, edit the `Desktop/sidorares/node-mysql2/test/integration/test-pool-release-idle-connection.test.cjs` to include your test case.

Finally, test it:

```
docker compose up
```

> Then, press `Ctrl + C` to exit.

As it should be a case not covered, it's expected to exit with `code 1` (error).
