### ISSUE TITLE
Close old PR's

### ISSUE THREAD

**Issue by jacobbogers** [sidorares/node-mysql2#3099]
Hi, there are PR's more then 4 years old, 
Maybe these should just be closed

**Comment by sidorares** [comment]
maybe, but probably not automatically

**Comment by wellwelwel** [comment]
> maybe, but probably not automatically

I use a **GitHub** bot to do that.

I set `X` deadline for an Issue/PR to become obsolete, then it sends a comment saying that if there is no new interaction in `Y` days, it will be closed.

We can use `labels` to determine categories that should not be made obsolete, for example: `bug`, `priority`, etc.

A functional example:

```yml
name: '🧹 Bot — Stale'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    name: Issues and PRs
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue-message: 'This issue has been closed due to inactivity for 15 days.'
          close-pr-message: 'This PR has been closed due to inactivity for 15 days.'
          stale-issue-message: ''
          stale-pr-message: ''
          days-before-stale: 13
          days-before-close: 2
          delete-branch: false
          enable-statistics: true
          exempt-issue-labels: 'enhancement,feature request,bug,priority'
```
