### ISSUE TITLE
Timezone bug: clearly documented

### ISSUE THREAD

**Issue by sjb933** [sidorares/node-mysql2#877]
There is a clear bug when specifying database timezones that is easily reproducible.

**Knex.js migration script, written in typescript**
```typescript
import * as Knex from 'knex';

const testTbl = 'TestTime';
const testCol = 'dt';

interface T { id: number; dt: Date };

module.exports = {
    up: async (knex: Knex) => {
        await knex.schema.createTableIfNotExists(testTbl, (t) => {
            t.increments('id').primary();
            t.dateTime(testCol);
        })

        console.log('\n\nDUMPING TABLE\n\n');
        await knex(testTbl).delete();

        const dt = new Date();
        console.log('Creating record with date:', dt.toISOString());
        await knex(testTbl).insert({ dt });

        const [record]: T[] = await knex(testTbl);
        console.log('Record returned with date', record.dt.toISOString());

        console.log('Updating record with same date');
        await knex(testTbl).update({ dt: record.dt }).where({ id: record.id });

        console.log('Record returned', (await knex(testTbl))[0].dt.toISOString());
        console.log('\n\nTEST END');
    },
    down: () => Promise.resolve()
}
```

**RESULTS FROM 4 EXECUTIONS, MYSQL VS MYSQL2, LOCAL VS UTC**
```yaml
Run 1: | # (PASS) DRIVER: MYSQL,  TIMEZONE: LOCAL (default)
  - 'Creating record with date: 2018-11-12T19:45:23.157Z'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 13:45:23"' # Date stored in DB as local time...
  - 'Record returned with date 2018-11-12T19:45:23.000Z' # Date parsed correctly
  - 'Updating record with same date'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 13:45:23"'
  - 'Record returned 2018-11-12T19:45:23.000Z' # Date is stable over reads/writes

Run 2: | # (PASS) DRIVER: MYSQL2,  TIMEZONE: LOCAL (default)
  - 'Creating record with date: 2018-11-12T19:47:39.630Z'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 13:47:40"' # Date stored in DB as local time...
  - 'Record returned with date 2018-11-12T19:47:40.000Z' # Date parsed correctly
  - 'Updating record with same date'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 13:47:40"'
  - 'Record returned 2018-11-12T19:47:40.000Z' # Date is stable over reads/writes

Run 3: | # (PASS) DRIVER: MYSQL,  TIMEZONE: UTC
  - 'Creating record with date: 2018-11-12T19:49:08.182Z'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 19:49:08 UTC"' # Date stored in DB as UTC (yay!)
  - 'Record returned with date 2018-11-12T19:49:08.000Z' # Date parsed correctly 
  - 'Updating record with same date'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 19:49:08 UTC"'
  - 'Record returned 2018-11-12T19:49:08.000Z' # Date is stable over reads/writes

Run 4: | # (FAIL) DRIVER: MYSQL2,  TIMEZONE: UTC
  - 'Creating record with date: 2018-11-12T19:50:58.551Z' 
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-12 19:50:59"' # Date stored in DB as UTC (yay!)
  - 'Record returned with date 2018-11-13T01:50:59.000Z' # DATE PARSING WRONG!
  - 'Updating record with same date'
  - 'MYSQL DRIVER: Parsing new date from DB "2018-11-13 01:50:59"' # DATE NOT STABLE
  - 'Record returned 2018-11-13T07:50:59.000Z'
```

**Observation:**
MYSQL2 mishandles timezones.  If you've supplied a timezone setting, it affects serializing _to_ the DB, but NOT deserializing _from_ the DB.
